version: "3"

services:
  selenium-edge:
    image: selenium/standalone-edge
    shm_size: 2gb
    ports:
      - "4444:4444"
    restart: always
  java-tests:
    build: .
    command: mvn -f pom.xml clean test
    depends_on:
      - selenium-edge